language: python

install:
  pip3 install flake8

jobs:
  include:
    - stage: lint 
      install: pip install lintly
      script: flake8 . --exit-zero --ignore=W191,E265 | lintly --format=flake8

stages:
  lint
